$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME=Eternal-Arctic
$ICON_THEME=Papirus-Nordic
$CURSOR_THEME=Capitaine-Cursors-Nord
$COLOR_SCHEME=prefer-dark
$CURSOR_SIZE=20
$CODE_THEME=Nord

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    border_size = 3
    col.inactive_border = rgba(434c5ebb) # Nord Polar Night (no. 1) with reduced opacity
    col.active_border = rgba(d8dee9ee) rgba(88c0d0cc) rgba(88c0d0cc) rgba(d8dee9ee) 45deg # Nord Snow Storm and Frost
    resize_on_border = yes
    gaps_in = 5
    gaps_out = 10
}

decoration {
    rounding = 12
    rounding_power = 2.0

    active_opacity = 1.0
    inactive_opacity = 0.95

    blur {
        enabled = false
        size = 5
        passes = 4
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.0
        popups = true
    }

    dim_inactive = true
    dim_strength = 0.05

    shadow {
        enabled = true
        range = 3
        render_power = e
        scale = 2
        sharp = true
        color = rgba(243, 240, 180, 1)
    }
}

group {
    col.border_inactive = rgba(434c5ebb) # Nord Polar Night (no. 1)
    col.border_active = rgba(d8dee9ee) rgba(88c0d0cc) rgba(88c0d0cc) rgba(d8dee9ee) 45deg # Nord Snow Storm and Frost

    groupbar {
      col.active = rgba(88c0d0cc) # Nord Frost (no. 2) with opacity
      col.inactive = rgba(4c566aff) # Nord Polar Night (no. 3)
      font_family = JetBrainsMono NFM
      font_size = 10
      text_color = rgba(d8dee9ff) # Nord Snow Storm (no. 1)
    }
}


blurls = waybar


